name:  Publish to Nuget
description: Build , Publish, Pack and Push  a project to nuget 
inputs:
  project_path:
    description: relative project path
    required: true
  package_name:
    description: package name in nuget
    required: true
  package_version:
    description: package version display in nuget
    required: true
  nuget_api_key:
    description: nuget api key
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # replace with desired version

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project_path }}
      shell: bash

    - name: Build and pack project
      run: dotnet pack -c Release --include-symbols -p:PackageVersion=${{ inputs.package_version }}  -o bin/Release --include-source ${{ inputs.project_path }}
      shell: bash

    - name: Publish package to NuGet
      run: dotnet nuget push bin/Release/${{ inputs.package_name }}.${{ inputs.package_version }}.nupkg --api-key ${{ inputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json
      shell: bash
      env:
        NUGET_API_KEY: ${{ inputs.nuget_api_key }}